### ISSUE TITLE
DAG support?

### ISSUE THREAD

**Issue by maxkfranz** [chuckzel/cytoscape-tidytree#1]
Does this layout currently support DAGs?

**Comment by chuckzel** [comment]
No, the code currently assumes that every node has a single incoming edge. It should be possible for the user to create a spanning tree from their graph and call the layout on a collection with only the edges in this tree included.

**Comment by maxkfranz** [comment]
That's what I suspected based on the paper.  Thanks for the clarification.

**Comment by chuckzel** [comment]
In 0.2.0, the layout now ignores other-than-first incoming edges just so it doesn't completely break on DAGs. A more sophisticated algorithm to get a better spanning tree is probably outside the scope of this library.
